### ISSUE TITLE
get_entity_groups_by_type() returns always none

### ISSUE THREAD

**Issue by jaimef1603** [thingsboard/python_tb_rest_client#1]
missing "return" in https://github.com/thingsboard/python_tb_rest_client/blob/89faedd08e151c2736506159109cc31fa785e9c2/tb_rest_client/rest_client_pe.py#L182

**Comment by zbeacon** [comment]
Hi @jaimef1603 

Thank you for your feedback, we have fixed it in https://github.com/thingsboard/python_tb_rest_client/commit/506272cc8317548596f4868146427d670b9055e3 .
