### ISSUE TITLE
get_tenant_devices() always return invalid UUID

### ISSUE THREAD

**Issue by Marchel-Ace** [thingsboard/python_tb_rest_client#2]
i want to get devices list, but always return like this

HTTP response body: {"status":400,"message":"Invalid UUID string: devices","errorCode":31,"timestamp":"2020-07-15T01:43:38.331+0000"}

**Comment by zbeacon** [comment]
Hi @Marchel-Ace ,

Thank you for your interest in the Python ThingsBoard REST client. Please share a part of your code with this function calling. It looks like ID has a different type that required.

**Comment by Marchel-Ace** [comment]
i just doing like this, using default value

` devices = rest_client.get_tenant_devices()`

and get error like this

`HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Type': 'application/json;charset=ISO-8859-1', 'Content-Length': '113', 'Date': 'Thu, 16 Jul 2020 06:12:06 GMT', 'Connection': 'close'})
HTTP response body: {"status":400,"message":"Invalid UUID string: devices","errorCode":31,"timestamp":"2020-07-16T06:12:06.757+0000"}`

thank you for the support

**Comment by Marchel-Ace** [comment]
i try to get dashboard_id and then i get this

`HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 16 Jul 2020 08:00:21 GMT', 'Connection': 'close'})
HTTP response body: {"timestamp":"2020-07-16T08:00:21.881+0000","status":400,"error":"Bad Request","message":"Parameter conditions \"pageSize, page\" not met for actual request parameters: limit={100000}","path":"/api/tenant/xxxx/dashboards"}`

this is my code 
` tenant = self.RestClient.get_user()`
 `tenant_id = tenant.tenant_id`
`dasboard = self.RestClient.get_tenant_dashboards(tenant_id=tenant_id)`

**Comment by zbeacon** [comment]
Hi @Marchel-Ace ,

Could you try to use the version 1.1.0 of the rest client? Please try and let me know about the results.

**Comment by shivams** [comment]
@zbeacon These API calls actually work for old versions of Thingsboard (v2.x) but not for latest releases (v3.x). There is a difference in the APIs in these versions. E.g. for `getTenantDevices`:
* In v2.x, the keys are : `type,textSearch,idOffset,textOffset,limit`
* In v3.x, the keys are : `type,textSearch,sortProperty,sortOrder,pageSize,page`

The Python client works only for the v2.x and NOT for the v3.x.

**Comment by zbeacon** [comment]
@shivams  
Thank you for your investigation, we will create a new branch with the REST client for 3.x. I will write here when it will be created.

**Comment by morcoGreen** [comment]
Any news about this? still can't get devices using Thingsboard 3.3.0 with rest 1.1.0
