### ISSUE TITLE
rest_client.get_timeseries() return

### ISSUE THREAD

**Issue by jaimef1603** [thingsboard/python_tb_rest_client#3]
`RestClient.get_timeseries()` method returns an object of type `DeferredResultResponseEntity` which always has following properties: 

```
{
    'result': None,
    'set_or_expired': None
}
```
I have tried the same requests to same urls and same parameters using plain python requests library and I get  correct results (actual timeseries data I have  saved in thingsboard), so I dont know why the result property is None when I use  `get_timeseries()` method. What is the correct way of extracting  the result from  `DeferredResultResponseEntity` object?

**Comment by zbeacon** [comment]
Hi @jaimef1603 ,

You can try to use the code like following, just replace some values:

```

import logging
# Importing models and REST client class from Professional Edition version
from tb_rest_client.rest_client_pe import *
from time import time
from tb_rest_client.rest import ApiException
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')
# ThingsBoard REST API URL
url = "http://localhost:8080"
# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"
# Creating the REST client object with context manager to get auto token refresh
def main():
    with RestClientPE(base_url=url) as rest_client:
        try:
            # Auth with credentials
            rest_client.login(username=username, password=password)
            entity_id = EntityId("DEVICE", "b8a718c0-d550-11ea-9c98-a75a5432dc3b")
            end_ts = int(time()*1000)
            x = rest_client.get_timeseries(entity_id, 'humidity', use_strict_data_types=False, start_ts=1, end_ts=end_ts)
            logging.info(x)
        except ApiException as e:
            logging.exception(e)
        except Exception as e:
            logging.exception(e)
if __name__ == '__main__':
    main()

```

**Comment by gaurav36** [comment]
@imbeacon  , I am also getting result as None but for the entity I am using Tenent eg: entity_id = EntityId('43674850-11111-11eb-b40e-4f4f7lik8459', 'TENANT')

do you know if its possible to get historical time-series data from all devices  for particular tenant, or particular customers?
